package assignment6;

// Greedy Method
// To apply Greedy method to solve problems of:

/*
   1) Job sequencing with deadlines:
      1. A) Generate table of feasible, processing sequencing, profit.
      1. B) What is the solution generated by the function JS when n=7, (p1,p2,p3,...,p7)=(3,5,20,18,1,6,30), and (d1,d2,d3,...,d7)=(1,3,4,3,2,1,2) ?
      1. C) Input: Five Jobs with following deadlines and profits:

            JobID=(a,b,c,d,e)
            Deadline=(2,1,2,1,3)
            Profit=(100,19,27,25,15)

          Output: Following is maximum profit sequence of jobs:
                  c, a, e
      1. D) Study and implement Disjoint set algorithm to reduce time complexity of JS from O(n^2) to nearly O(n).
*/


public class Example1 {

    public static void main(String[] args) {

    }

}
